### ISSUE TITLE
Warning: Prop `dangerouslySetInnerHTML` did not match. Server: ... Client ...

### ISSUE THREAD

**Issue by spc16670** [timhagn/gatsby-background-image#149]
I upgraded to gatsby 3 and now I am always getting this error on initial page load, hot reloads does not regenerate it:

Does not matter what props are set on BackgroundImage

`react-dom.development.js:67 Warning: Prop `dangerouslySetInnerHTML` did not match. Server: "\n          .gbi-1896301322-ua3MpzFV6SZcJ1ruEkiBab:before,\n          .gbi-1896301322-ua3MpzFV6SZcJ1ruEkiBab:after {\n            content: '';\n            display: block;\n            position: absolute;\n            width: 100%;\n            height: 100%;\n            top: 0;\n            left: 0;\n            background-color: #040e18;\n            transition: opacity 0.5s ease 250ms;\n            background-position: center;\nbackground-repeat: no-repeat;\nbackground-size: cover;\n\n          }\n          .gbi-1896301322-ua3MpzFV6SZcJ1ruEkiBab:before {\n            z-index: -100;\n            \n            \n            opacity: 1; \n          }\n          .gbi-1896301322-ua3MpzFV6SZcJ1ruEkiBab:after {\n            z-index: -101;\n            \n            \n            \n          }\n        " Client: "\n          .gbi-1896301322-m94RwuVekReako9Rfi9cBG:before,\n          .gbi-1896301322-m94RwuVekReako9Rfi9cBG:after {\n            content: '';\n            display: block;\n            position: absolute;\n            width: 100%;\n            height: 100%;\n            top: 0;\n            left: 0;\n            background-color: #040e18;\n            transition: opacity 0.5s ease 250ms;\n            background-position: center;\nbackground-repeat: no-repeat;\nbackground-size: cover;\n\n          }\n          .gbi-1896301322-m94RwuVekReako9Rfi9cBG:before {\n            z-index: -100;\n            background-image: url(\"data:image/svg+xml,%3csvg%20xmlns='http://www.w3.org/rule='evenodd'/%3e%3c/svg%3e\");\n            \n            opacity: 1; \n          }\n          .gbi-1896301322-m94RwuVekReako9Rfi9cBG:after {\n            z-index: -101;\n            \n            \n            \n          }\n        "
    at style
    at div
    at BackgroundImage (webpack-internal:///./node_modules/gatsby-background-image/index.js:51:30)
    at SplashCoverImage (webpack-internal:///./src/components/images/backgrounds/bg1-cover.js:23:24)
    at MDXCreateElement (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at div`

My deps are:

        "gatsby": "^3.0.4",
        "gatsby-background-image": "^1.4.1",
        "gatsby-image": "^3.0.0",
        "gatsby-plugin-manifest": "^3.0.0",
        "gatsby-plugin-mdx": "^2.0.1",
        "gatsby-plugin-offline": "^4.0.0",
        "gatsby-plugin-react-helmet": "^4.0.0",
        "gatsby-plugin-sass": "^4.0.2",
        "gatsby-plugin-sharp": "^3.0.1",
        "gatsby-plugin-sitemap": "^3.0.0",
        "gatsby-plugin-styled-components": "^4.0.0",
        "gatsby-remark-images": "^4.0.0",
        "gatsby-source-filesystem": "^3.0.0",
        "gatsby-transformer-json": "^3.0.0",
        "gatsby-transformer-sharp": "^3.0.0",

Tried clearing cache and deleting public folder but this warning message does not go away.

**Comment by timhagn** [comment]
Hi @spc16670!

Uffz, hard to tell from solely the error message, but from the last line it originates in `MDXCreateElement` so probably only in combination with `gatsby-plugin-mdx`... Could you create a reproduction repo so that I could look into it further?

Best,

Tim.

**Comment by spc16670** [comment]
I am extremely pressed for deadlines at the moment, not sure I will find time to reproduce online. I keep seeing the error though randomly every now and then when gatsby does a full re-render:

Here is another stack trace, this one not related to BackgroundImage but it would appear to text changing in <a> tag...

```
react-dom.development.js:67 Warning: Text content did not match. Server: "Services" Client: "Oferta"
    at a
    at SafeAnchor (webpack-internal:///./node_modules/react-bootstrap/esm/SafeAnchor.js:24:22)
    at eval (webpack-internal:///./node_modules/react-bootstrap/esm/AbstractNavItem.js:24:21)
    at NavLink (webpack-internal:///./node_modules/react-bootstrap/esm/NavLink.js:22:23)
    at DropdownToggle (webpack-internal:///./node_modules/react-bootstrap/esm/DropdownToggle.js:25:23)
    at div
    at ReactOverlaysDropdown (webpack-internal:///./node_modules/react-overlays/esm/Dropdown.js:112:19)
    at Dropdown (webpack-internal:///./node_modules/react-bootstrap/esm/Dropdown.js:46:89)
    at NavDropdown (webpack-internal:///./node_modules/react-bootstrap/esm/NavDropdown.js:18:17)
    at li
    at NavItem (webpack-internal:///./node_modules/react-bootstrap/esm/NavItem.js:15:23)
    at ul
    at eval (webpack-internal:///./node_modules/react-bootstrap/esm/AbstractNav.js:25:22)
    at Nav (webpack-internal:///./node_modules/react-bootstrap/esm/Nav.js:35:89)
    at div
    at Transition (webpack-internal:///./node_modules/react-transition-group/esm/Transition.js:129:30)
    at eval (webpack-internal:///./node_modules/react-bootstrap/esm/Collapse.js:48:22)
    at NavbarCollapse (webpack-internal:///./node_modules/react-bootstrap/esm/NavbarCollapse.js:15:23)
    at div
    at Container (webpack-internal:///./node_modules/react-bootstrap/esm/Container.js:17:23)
    at nav
    at Navbar (webpack-internal:///./node_modules/react-bootstrap/esm/Navbar.js:36:89)
    at Navbar (webpack-internal:///./src/components/navbar/navbar.js:67:23)
    at div
    at div
    at Layout (webpack-internal:///./src/components/layout/layout.js:28:23)
    at LandingTemplate (webpack-internal:///./src/templates/landing.js:61:20)
    at I18nextProvider (webpack-internal:///./node_modules/react-i18next/dist/es/I18nextProvider.js:10:19)
    at WrapWithIntl (webpack-internal:///./src/components/with-intl.hoc.js:35:30)
    at PageRenderer (webpack-internal:///./.cache/page-renderer.js:30:29)
    at PageQueryStore (webpack-internal:///./.cache/query-result-store.js:46:30)
    at RouteHandler
    at div
    at FocusHandlerImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:359:5)
    at FocusHandler (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:330:19)
    at RouterImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:235:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Router
    at ScrollHandler (webpack-internal:///./node_modules/gatsby-react-router-scroll/scroll-handler.js:34:35)
    at RouteUpdates (webpack-internal:///./.cache/navigation.js:304:32)
    at EnsureResources (webpack-internal:///./.cache/ensure-resources.js:29:30)
    at LocationHandler (webpack-internal:///./.cache/root.js:67:29)
    at LocationProvider (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:84:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Root
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at MDXScopeProvider (webpack-internal:///./node_modules/gatsby-plugin-mdx/context.js:32:25)
    at _c (webpack-internal:///./node_modules/gatsby-plugin-mdx/wrap-root-element.js:136:37)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:122:48)
    at GlobalContextProvider (webpack-internal:///./src/providers/global-context.js:49:23)
    at StaticQueryStore (webpack-internal:///./.cache/query-result-store.js:134:32)
    at ErrorBoundary (webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:24:35)
    at DevOverlay (webpack-internal:///./.cache/fast-refresh-overlay/index.js:104:23)
    at RootWrappedWithOverlayAndProvider
```

**Comment by timhagn** [comment]
Hi @spc16670 ,

would probably be better to open up this one over at the gatsby repo itself. Cause to the latter I can relate,
hot-reloading was a little mess during my latest developing forays...

But as it's only a `warning` you should be good as is ; ).

Best,

Tim.

**Comment by ferrefabio1987** [comment]
I have idem error:

```
index.js:2177 Warning: Prop `dangerouslySetInnerHTML` did not match. Server: "\n          .makeStyles-bgImg-13:before,\n          .makeStyles-bgImg-13:after {\n            content: '';\n            display: block;\n            position: absolute;\n            width: 100%;\n            height: 100%;\n            top: 0;\n            left: 0;\n            \n            transition: opacity 0.5s ease 250ms;\n            background-position: center;\nbackground-repeat: no-repeat;\nbackground-size: cover;\n\n          }\n          .makeStyles-bgImg-13:before {\n            z-index: -100;\n            \n            \n            opacity: 1; \n          }\n          .makeStyles-bgImg-13:after {\n            z-index: -101;\n            \n            \n            \n          }\n        " Client: "\n          .makeStyles-bgImg-13:before,\n          .makeStyles-bgImg-13:after {\n            content: '';\n            display: block;\n            position: absolute;\n            width: 100%;\n            height: 100%;\n            top: 0;\n            left: 0;\n            \n            transition: opacity 0.5s ease 250ms;\n            background-position: center;\nbackground-repeat: no-repeat;\nbackground-size: cover;\n\n          }\n          .makeStyles-bgImg-13:before {\n            z-index: -100;\n            background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAqCAIAAAA8m+yHAAAACXBIWXMAAHUwAAB1MAHdM3LNAAACRElEQVRIx42Wy5aCQAxE+f+f9AGKiMAwzCDuJt3VVJfBw5laeNxc8+ikYnG9Xm+3W9M09/v98Xh0XTcMw9eqcRy/o6Zp+on6jZrn+fl8FpfLpa5rI403uO/7IYo8yD24iWJkwPiisJIBtrQBW/C2bTU4f8WlDXhZlhAZZSNz4y24Jo+yDf5dZfASldJmzwzuVyFz9oxpI+cEm5pVCGvqogCDdzmHmquqMlhfC2Ujc8QHz8xzzVWUkSi7jULbweuD+Yadz2eD0TPwCN6t0shoeK4ZsLYNMDtHeNuz4nQ6lWXJB8O0QYy8LRvJBxjBkTynjdPKyhEZwe0zwMfj0WALjuS5J2w+k+eGsHMpchmFN2PndNpYtva80Jgm5oyamfMkyjWz4DoKGEjk7BaTBQdYSzW4XYWw2uoPK6mPbNJHdpaAVpNMsK70Q7QzXnm28TY61doqt5Ic7ARzMFgqF9NFVicIMJ+H7kkz2DoBCzby9XolmB6kBsSpNHGkCefIeFuNrNat1gk+wa7PuglMe+u7bzBN24XdMe0AYwe4QPu3Zl6VYXeo1LFRsAY3MjuJpU3Td5uk8RmcPxEWQw3gnzCTTxPmkteG87V0k9OVNDPgYtiQaOe250oj560yYcj0XAEeV21vXYrMOeOVdbwblWz62jMsFqXu9+HcwAC5W+pB7tapb6d3dqbLzGGAdDJmbsoeBtOGjbHn6kTOEtC2t1tFDwUPD9y/dfncqAFzVBXe+lE4N4fDARcH/y+QvGH8l6EGbpjO6R959i0lyLvnKQAAAABJRU5ErkJggg==);\n            \n            opacity: 1; \n          }\n          .makeStyles-bgImg-13:after {\n            z-index: -101;\n            \n            \n            \n          }\n        "
    in style (created by BackgroundImage)
    in section (created by BackgroundImage)
    in BackgroundImage (at layout.js:53)
    in div (at layout.js:46)
    in div (at layout.js:43)
    in Layout (at pages/index.js:110)
    in IndexPage (created by HotExportedIndexPage)
    in AppContainer (created by HotExportedIndexPage)
    in HotExportedIndexPage (created by ReplaceComponentRenderer)
    in ReplaceComponentRenderer (created by PageRenderer)
    in Wrapper (created by PageRenderer)
    in PageRenderer (at query-result-store.js:90)
    in PageQueryStore (at root.js:57)
    in RouteHandler (at root.js:79)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (at root.js:74)
    in ScrollHandler (at root.js:70)
    in RouteUpdates (at root.js:69)
    in EnsureResources (at root.js:67)
    in LocationHandler (at root.js:125)
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:124)
    in Root (at root.js:132)
    in ThemeProvider (at top-layout.js:11)
    in TopLayout (at wrap-with-provider.js:7)
    in StylesProvider
    in CorniceContextProvider (at gatsby-browser.js:10)
    in GiftContextProvider (at gatsby-browser.js:9)
    in StaticQueryStore (at root.js:149)
    in ConditionalFastRefreshOverlay (at root.js:148)
    in _default (at app.js:165)
```

**Comment by ehannes** [comment]
@spc16670 did you manage to solve this problem? I'm seeing the same warning.

**Comment by matthewkwong2** [comment]
> Hi @spc16670 ,
> 
> would probably be better to open up this one over at the gatsby repo itself. Cause to the latter I can relate,
> hot-reloading was a little mess during my latest developing forays...
> 
> But as it's only a `warning` you should be good as is ; ).
> 
> Best,
> 
> Tim.

@timhagn 
Even though this is a warning, it is in fact affecting re-hydration performance by a considerable amount. For me, the reason the CSS does not match is that the pre-rendered CSS is missing the following two attributes.
1. `background-color`, if it is set
2. `background-image`, i.e. the blurry placeholder/tracing SVG
This is another reason why I strongly encourage you to embed the placeholder to the CSS itself besides better UX.

**Comment by matthewkwong2** [comment]
Just to prove how this issue affects performance.
This is my webpage using `gatsby-background-image`: https://494bfb5e.resume-gatsby.pages.dev/
This is my webpage using `gatsby-plugin-image` as a replacement: https://5aaade0a.resume-gatsby.pages.dev/

https://lighthouse-metrics.com/one-time-tests/6093a8e43355d0000aff94e6
https://lighthouse-metrics.com/one-time-tests/6093a90d864f2e00091ac4e2
